type Circle @entity {
  id: ID!
  name: String! # Circle Name
  circleId: String! # Circle ID
  owner: String! # Owner Address
  token: String! # Token Address

  stake: [CircleStake!]! @derivedFrom(field: "circle")
}

type CircleStake @entity {
  id: ID!
  circleId: String! # Circle ID
  amount: BigInt! # Staked Amount
  stakedBy: String! # Staked By Address

  Circle: Circle! @derivedFrom(field: "stake")
}


type Staker @entity {
  id: ID!
  
  totalStaked: BigInt! # Total Staked Amount

  claimableRewards: [StakerClaimableRewards!]! @derivedFrom(field: "staker")
  earnedRewards: [StakerEarnedRewards!]! @derivedFrom(field: "staker")

  stakedCircles: [String!]! # Staked Circles ids
}

type StakerEarnedRewards @entity {
  id: ID!
  staker: String! # Staker Address
  circleId: String! # Circle ID
  earnedRewards: BigInt! # Earned Rewards Amount
  earnedAt: BigInt! # Earned At
}

type StakerClaimableRewards @entity {
  id: ID!
  staker: String! # Staker Address
  circleId: String! # Circle ID
  claimableRewards: BigInt! # Claimable Rewards Amount
  claimableAt: BigInt! # Claimable At
}

type CircleMetrics @entity {
  id: ID!
  circleId: String! # Circle ID

  circleTotalVolume: BigInt! # Total Volume

  totalStaked: BigInt! # Total Staked Amount
  adminStaked: BigInt! # Admin Staked Amount

  totalMerchantsCount: BigInt! # Total Merchants Count
  activeMerchantsCount: BigInt! # Active Merchants Count

  totalDisputesCount: BigInt! # Total Disputes Count
  pendingDisputesCount: BigInt! # Pending Disputes Count
  resolvedDisputesCount: BigInt! # Resolved Disputes Count
  challengedDisputesCount: BigInt! # Challenged Disputes Count
}
