export const STAKE_HISTORY_TYPE_STAKED: string = "STAKED";
export const STAKE_HISTORY_TYPE_UNSTAKE_REQUESTED: string = "UNSTAKE_REQUESTED";
export const STAKE_HISTORY_TYPE_UNSTAKE_REJECTED: string = "UNSTAKE_REJECTED";
export const STAKE_HISTORY_TYPE_UNSTAKE_APPROVED: string = "UNSTAKE_APPROVED";
export const STAKE_HISTORY_TYPE_DELEGATED: string = "DELEGATED";
export const STAKE_HISTORY_TYPE_UNDELEGATED: string = "UNDELEGATED";
